//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DolphinApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DolphinEntities : DbContext
    {
        public DolphinEntities()
            : base("name=DolphinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<division> division { get; set; }
        public virtual DbSet<dolphinmatch> dolphinmatch { get; set; }
        public virtual DbSet<piscine> piscine { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
    }
}
