//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DolphinApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dolphinmatch
    {
        public int ID_MATCH { get; set; }
        public System.DateTime DATE_MATCH { get; set; }
        public bool SECOND_MATCH { get; set; }
        public decimal DISTANCE { get; set; }
        public decimal COUT { get; set; }
        public int ID_PISCINE { get; set; }
        public int ID_DIVISION { get; set; }
        public int ID_UTILISATEUR { get; set; }
    
        public virtual division division { get; set; }
        public virtual piscine piscine { get; set; }
        public virtual utilisateur utilisateur { get; set; }
    }
}
